name: Upstream Sync

on:
  schedule:
    - cron: '0 3 * * *'   # Daily at 03:00 UTC
  workflow_dispatch:
    inputs:
      sync_test_mode:
        description: 'Fork Sync Test Mode'
        type: boolean
        default: false

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    name: Sync latest commits from upstream repo

    strategy:
      matrix:
        branch: [main, dev, hacking]  # List all branches you want to sync

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3
        with:
          ref: ${{ matrix.branch }}
          persist-credentials: false

      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          target_sync_branch: ${{ matrix.branch }}
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_branch: ${{ matrix.branch }}
          upstream_sync_repo: frdel/agent-zero
          # Optional: If upstream is private, set a secret like UPSTREAM_REPO_SECRET
          # upstream_repo_access_token: ${{ secrets.UPSTREAM_REPO_SECRET }}
          git_fetch_args: '--tags'
          git_pull_args: '--ff-only'
          git_log_format_args: '--graph --pretty=oneline'
          test_mode: ${{ inputs.sync_test_mode }}

      - name: New commits found
        if: steps.sync.outputs.has_new_commits == 'true'
        run: echo "New commits were found to sync."

      - name: No new commits
        if: steps.sync.outputs.has_new_commits == 'false'
        run: echo "There were no new commits."

      - name: Show value of 'has_new_commits'
        run: echo ${{ steps.sync.outputs.has_new_commits }}
